### PR TITLE
Example of classes and loops (poorly written)

### PR DESCRIPTION
**Pull request by brianharringtonpersonal**

### CODE REVIEW

**Comment by brianharringtonpersonal** [comment]
This isn't a serious MR, just a little fun.

I haven't used python before, so I figured I'd give it a whirl. In this MR, I'm showing how you can use classes to store all your "data" up front, and then loop through those classes in the UI. This way, if you wanted to add more parts or ships, you just need to add them to the classes at the top of the file.

If you want to do more python development, I'd suggest you start breaking the script down into multiple files. It might seem trivial, but it'll help you get a firm grasp on separation of concerns & encapsulation - things you'll need to know to really "get" programming.

The styling in this MR is bad, and the code quality is bad. It's just a quick script whipped up to point you in a direction.

**Comment by Memememe16205** [comment]
Cool, thank you!

**Comment by brianharringtonpersonal** [comment]
There's a lot of good advice in the reddit thread, especially from fing-tree.

Merges actually apply the changes a developer made somewhere else into your repo. You may want to revert this MR if you didn't want to replace your work with mine. But if you want to start from what I had there, go for it.

**Comment by Memememe16205** [comment]
I’ll see what you put in and if it’s good, I’ll keep it :) Sent from my iPhoneOn Jul 12, 2023, at 1:42 PM, brianharringtonpersonal ***@***.***> wrote:﻿
There's a lot of good advice in the reddit thread, especially from fing-tree.
Merges actually apply the changes a developer made somewhere else into your repo. You may want to revert this MR if you didn't want to replace your work with mine. But if you want to start from what I had there, go for it.

**Pull request merged**
